## Max Voting

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('data_cleaned.csv')

In [3]:
data.shape

(891, 25)

In [4]:
data.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [5]:
#seperating independent and dependent variables

x = data.drop(['Survived'], axis=1)
y = data['Survived']

In [6]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, stratify=y)

In [7]:
#Scaling the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
valid_x = sc.transform(valid_x)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [9]:
model1 = LogisticRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0]), 0.7757847533632287)

In [10]:
model2 = KNeighborsClassifier(n_neighbors=5)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([0, 0, 0, 0, 1, 1, 0, 1, 1, 0]), 0.7802690582959642)

In [11]:
model3 = DecisionTreeClassifier(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0]), 0.7847533632286996)

In [12]:
# df = pd.DataFrame(columns=['M1', 'M2', 'M3', 'Actual'])
# df['M1'] = pred1
# df['M2'] = pred2
# df['M3'] = pred3
# df['Actual'] = np.array(valid_y)

In [13]:
from statistics import mode
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mode([pred1[i], pred2[i], pred3[i]]))

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy_score(valid_y, final_pred)

0.7892376681614349

In [16]:
accuracy_score(valid_y, pred1), accuracy_score(valid_y, pred2), accuracy_score(valid_y, pred3)

(0.7757847533632287, 0.7802690582959642, 0.7847533632286996)

## Averaging

In [17]:
import pandas as pd
import numpy as np

In [18]:
data=pd.read_csv('train_cleaned.csv')

In [19]:
data.shape

(8523, 46)

In [20]:
data.head()

Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year  \
0         9.30         0.016047  249.8092                       1999   
1         5.92         0.019278   48.2692                       2009   
2        17.50         0.016760  141.6180                       1999   
3        19.20         0.000000  182.0950                       1998   
4         8.93         0.000000   53.8614                       1987   

   Item_Outlet_Sales  Item_Fat_Content_LF  Item_Fat_Content_Low Fat  \
0          3735.1380                    0                         1   
1           443.4228                    0                         0   
2          2097.2700                    0                         1   
3           732.3800                    0                         0   
4           994.7052                    0                         1   

   Item_Fat_Content_Regular  Item_Fat_Content_low fat  Item_Fat_Content_reg  \
0                         0                         0                     0   
1                         1                         0                     0   
2                         0                         0                     0   
3                         1                         0                     0   
4                         0                         0                     0   

   ...  Outlet_Size_High  Outlet_Size_Medium  Outlet_Size_Small  \
0  ...                 0                   1                  0   
1  ...                 0                   1                  0   
2  ...                 0                   1                  0   
3  ...                 0                   0                  0   
4  ...                 1                   0                  0   

   Outlet_Location_Type_Tier 1  Outlet_Location_Type_Tier 2  \
0                            1                            0   
1                            0                            0   
2                            1                            0   
3                            0                            0   
4                            0                            0   

   Outlet_Location_Type_Tier 3  Outlet_Type_Grocery Store  \
0                            0                          0   
1                            1                          0   
2                            0                          0   
3                            1                          1   
4                            1                          0   

   Outlet_Type_Supermarket Type1  Outlet_Type_Supermarket Type2  \
0                              1                              0   
1                              0                              1   
2                              1                              0   
3                              0                              0   
4                              1                              0   

   Outlet_Type_Supermarket Type3  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  

[5 rows x 46 columns]

In [21]:
#seperating independent and dependent variables
x = data.drop(['Item_Outlet_Sales'], axis=1)
y = data['Item_Outlet_Sales']

In [22]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [23]:
#Scaling the features
train_x = sc.fit_transform(train_x)
valid_x = sc.transform(valid_x)

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [25]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2435.06569788,  2789.06569788,  2173.06569788,  2379.06569788,
         2707.06569788,  3767.06569788,  5146.56569788,  4146.56569788,
        -1010.93430212,  1355.06569788]), 0.5554499637693046)

In [26]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1832.79944444, 3296.89364444,  588.04935556, 2832.53513333,
        1960.92895556, 2985.74311111, 5198.86231111, 3343.35168889,
         188.34742222, 1433.61535556]), 0.4718115979265173)

In [27]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]), 0.5735129516531656)

In [28]:
valid_y

6392    4277.7650
6393    1070.6064
6394    1001.3632
6395    2871.5954
6396    4287.7520
          ...    
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 2131, dtype: float64

In [29]:
df = pd.DataFrame(columns=['M1', 'M2', 'M3', 'Actual'])
df['M1'] = pred1
df['M2'] = pred2
df['M3'] = pred3
df['Actual'] = np.array(valid_y)
# df['Actual'] = valid_y
df.head()

M1           M2           M3     Actual
0  2435.065698  1832.799444  2413.817763  4277.7650
1  2789.065698  3296.893644  2822.719131  1070.6064
2  2173.065698   588.049356   585.226311  1001.3632
3  2379.065698  2832.535133  2348.861121  2871.5954
4  2707.065698  1960.928956  3153.224868  4287.7520

In [30]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred2[i], pred3[i]]))

In [31]:
final_pred

array([2227.22763515, 2969.55949116, 1115.44712138, ..., 1526.94802226,
       1535.93086272, 1162.50385193])

In [32]:
from sklearn.metrics import r2_score

In [33]:
r2_score(valid_y, final_pred)

0.5751437545889124

In [34]:
r2_score(valid_y, pred1), r2_score(valid_y, pred2), r2_score(valid_y, pred3)

(0.5554499637693046, 0.4718115979265173, 0.5735129516531656)

## Weighted Averaging

In [35]:
import pandas as pd
import numpy as np

In [36]:
data=pd.read_csv('train_cleaned.csv')

In [37]:
data.shape

(8523, 46)

In [38]:
data.head()

Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year  \
0         9.30         0.016047  249.8092                       1999   
1         5.92         0.019278   48.2692                       2009   
2        17.50         0.016760  141.6180                       1999   
3        19.20         0.000000  182.0950                       1998   
4         8.93         0.000000   53.8614                       1987   

   Item_Outlet_Sales  Item_Fat_Content_LF  Item_Fat_Content_Low Fat  \
0          3735.1380                    0                         1   
1           443.4228                    0                         0   
2          2097.2700                    0                         1   
3           732.3800                    0                         0   
4           994.7052                    0                         1   

   Item_Fat_Content_Regular  Item_Fat_Content_low fat  Item_Fat_Content_reg  \
0                         0                         0                     0   
1                         1                         0                     0   
2                         0                         0                     0   
3                         1                         0                     0   
4                         0                         0                     0   

   ...  Outlet_Size_High  Outlet_Size_Medium  Outlet_Size_Small  \
0  ...                 0                   1                  0   
1  ...                 0                   1                  0   
2  ...                 0                   1                  0   
3  ...                 0                   0                  0   
4  ...                 1                   0                  0   

   Outlet_Location_Type_Tier 1  Outlet_Location_Type_Tier 2  \
0                            1                            0   
1                            0                            0   
2                            1                            0   
3                            0                            0   
4                            0                            0   

   Outlet_Location_Type_Tier 3  Outlet_Type_Grocery Store  \
0                            0                          0   
1                            1                          0   
2                            0                          0   
3                            1                          1   
4                            1                          0   

   Outlet_Type_Supermarket Type1  Outlet_Type_Supermarket Type2  \
0                              1                              0   
1                              0                              1   
2                              1                              0   
3                              0                              0   
4                              1                              0   

   Outlet_Type_Supermarket Type3  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  

[5 rows x 46 columns]

In [39]:
#seperating independent and dependent variables
x = data.drop(['Item_Outlet_Sales'], axis=1)
y = data['Item_Outlet_Sales']

In [40]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [41]:
#Scaling the features
train_x = sc.fit_transform(train_x)
valid_x = sc.transform(valid_x)

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [43]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2435.06569788,  2789.06569788,  2173.06569788,  2379.06569788,
         2707.06569788,  3767.06569788,  5146.56569788,  4146.56569788,
        -1010.93430212,  1355.06569788]), 0.5554499637693046)

In [44]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1832.79944444, 3296.89364444,  588.04935556, 2832.53513333,
        1960.92895556, 2985.74311111, 5198.86231111, 3343.35168889,
         188.34742222, 1433.61535556]), 0.4718115979265173)

In [45]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]), 0.5735374916724254)

In [46]:
# df = pd.DataFrame(columns=['M1', 'M2', 'M3', 'Actual'])
# df['M1'] = pred1
# df['M2'] = pred2
# df['M3'] = pred3
# df['Actual'] = np.array(valid_y)

In [47]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred1[i], pred2[i], pred3[i], pred3[i]]))

In [48]:
from sklearn.metrics import r2_score

In [49]:
r2_score(valid_y, final_pred)

0.5815426925474019

In [50]:
r2_score(valid_y, pred1), r2_score(valid_y, pred2), r2_score(valid_y, pred3)

(0.5554499637693046, 0.4718115979265173, 0.5735374916724254)

## Rank Averaging

In [51]:
import pandas as pd
import numpy as np

In [52]:
data=pd.read_csv('train_cleaned.csv')

In [53]:
data.shape

(8523, 46)

In [54]:
data.head()

Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year  \
0         9.30         0.016047  249.8092                       1999   
1         5.92         0.019278   48.2692                       2009   
2        17.50         0.016760  141.6180                       1999   
3        19.20         0.000000  182.0950                       1998   
4         8.93         0.000000   53.8614                       1987   

   Item_Outlet_Sales  Item_Fat_Content_LF  Item_Fat_Content_Low Fat  \
0          3735.1380                    0                         1   
1           443.4228                    0                         0   
2          2097.2700                    0                         1   
3           732.3800                    0                         0   
4           994.7052                    0                         1   

   Item_Fat_Content_Regular  Item_Fat_Content_low fat  Item_Fat_Content_reg  \
0                         0                         0                     0   
1                         1                         0                     0   
2                         0                         0                     0   
3                         1                         0                     0   
4                         0                         0                     0   

   ...  Outlet_Size_High  Outlet_Size_Medium  Outlet_Size_Small  \
0  ...                 0                   1                  0   
1  ...                 0                   1                  0   
2  ...                 0                   1                  0   
3  ...                 0                   0                  0   
4  ...                 1                   0                  0   

   Outlet_Location_Type_Tier 1  Outlet_Location_Type_Tier 2  \
0                            1                            0   
1                            0                            0   
2                            1                            0   
3                            0                            0   
4                            0                            0   

   Outlet_Location_Type_Tier 3  Outlet_Type_Grocery Store  \
0                            0                          0   
1                            1                          0   
2                            0                          0   
3                            1                          1   
4                            1                          0   

   Outlet_Type_Supermarket Type1  Outlet_Type_Supermarket Type2  \
0                              1                              0   
1                              0                              1   
2                              1                              0   
3                              0                              0   
4                              1                              0   

   Outlet_Type_Supermarket Type3  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  

[5 rows x 46 columns]

In [55]:
#seperating independent and dependent variables
x = data.drop(['Item_Outlet_Sales'], axis=1)
y = data['Item_Outlet_Sales']

In [56]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [57]:
#Scaling the features
train_x = sc.fit_transform(train_x)
valid_x = sc.transform(valid_x)

In [58]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [59]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2435.06569788,  2789.06569788,  2173.06569788,  2379.06569788,
         2707.06569788,  3767.06569788,  5146.56569788,  4146.56569788,
        -1010.93430212,  1355.06569788]), 0.5554499637693046)

In [60]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1832.79944444, 3296.89364444,  588.04935556, 2832.53513333,
        1960.92895556, 2985.74311111, 5198.86231111, 3343.35168889,
         188.34742222, 1433.61535556]), 0.4718115979265173)

In [61]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]), 0.5734613370524885)

In [62]:
m1_score= model1.score(valid_x, valid_y)
m2_score= model2.score(valid_x, valid_y)
m3_score= model3.score(valid_x, valid_y)
m1_score, m2_score, m3_score

(0.5554499637693046, 0.4718115979265173, 0.5734613370524885)

In [63]:
index_ = [1,2,3]
valid_r2 = [m1_score,m2_score,m3_score]

rank_eval = pd.DataFrame({
    'score':valid_r2
}, index = index_)
rank_eval

score
1  0.555450
2  0.471812
3  0.573461

In [64]:
sorted_rank = rank_eval.sort_values('score')
sorted_rank

score
2  0.471812
1  0.555450
3  0.573461

In [65]:
sorted_rank['rank'] = [i for i in range(1,4)]
sorted_rank

score  rank
2  0.471812     1
1  0.555450     2
3  0.573461     3

In [66]:
sorted_rank['weight'] = sorted_rank['rank']/sorted_rank['rank'].sum()
sorted_rank

score  rank    weight
2  0.471812     1  0.166667
1  0.555450     2  0.333333
3  0.573461     3  0.500000

In [67]:
wt_pred1 = pred1*float(sorted_rank.loc[[1],['weight']].values)
wt_pred2 = pred2*float(sorted_rank.loc[[2],['weight']].values)
wt_pred3 = pred3*float(sorted_rank.loc[[3],['weight']].values)
ranked_prediction = wt_pred1 + wt_pred2 + wt_pred3
ranked_prediction

array([2324.0640216 , 2890.53040561, 1114.97661391, ..., 1455.97127633,
       1533.78709999, 1223.90054677])

In [68]:
r2_score(valid_y, ranked_prediction)

0.5833327742118797